### ISSUE TITLE
Problem with cookie-cipher-secret-key	

### ISSUE THREAD

**Issue by luiscinfo** [OKDP/okdp-spark-auth-filter#24]
Im trying to add authentication to Spark using this filter. Im using: 

- Keycloak 
- Spark 3.5.1

Im identifying that there is something strange in terms of the cookie-cipher-secret-key. Im seeing this message (already logged in)

![image](https://github.com/OKDP/okdp-spark-auth-filter/assets/172381419/8a82726f-813e-4ceb-ab15-4a24844509f3)

To generate the key Im using the comand that is in the documentation: `openssl enc -aes-128-cbc -k <PASS PHRASE> -P -md sha1 -pbkdf2`. The output is this: 

![image](https://github.com/OKDP/okdp-spark-auth-filter/assets/172381419/3e62b630-97c0-4fec-a37b-b3f23a176aee)

Im putting the key value as the value of `cookie-cipher-secret-key`

It seams that there is an issue encoding and decoding but I don't seem to find the problem. ¿Is it possible that this is due to a wrong key cookie-key definition?

**Comment by idirze** [comment]
No, we have not hitted this issue before.
To help reproduce the issue from my side, what is the java base image and version you use to build your spark image?

Alternatively,  can you try with this image: ?

- quay.io/okdp/spark:spark-3.5.1-scala-2.13-java-17 or 
- quay.io/okdp/spark:spark-3.5.1-scala-2.12-java-17

**Comment by luiscinfo** [comment]
Im currently using this Spark image: bitnami/spark:3.5.1. I would like to try the images that you mention, ¿is it possible that you can provide me with a configuration example for docker-compose.yml with those images?

**Comment by idirze** [comment]
There is an issue, related to base64 encoding/decoding logic in the filter, with the bitnami jdk which does not happen in other JDKs distributions tested until now.
I have pushed a fix as a pre-release here: https://github.com/OKDP/okdp-spark-auth-filter/releases/tag/v1.2.2
Can you please, test with the jar [okdp-spark-auth-filter-1.2.2.jar](https://github.com/OKDP/okdp-spark-auth-filter/releases/download/v1.2.2/okdp-spark-auth-filter-1.2.2.jar) also included in the [Assets](https://github.com/OKDP/okdp-spark-auth-filter/releases/tag/v1.2.2)

**Comment by luiscinfo** [comment]
Hi @idirze , 

We have tested the change in 1.2.2 with bitnami/spark images (3.5.1 exactly) and it works correctly. We appreciate that you have taken the time to make the changes.

**Comment by idirze** [comment]
I close the issue. Fixed by [v1.2.2](https://github.com/OKDP/okdp-spark-auth-filter/releases/tag/v1.2.2).

**Comment by idirze** [comment]
I close the issue. Fixed by [v1.2.2](https://github.com/OKDP/okdp-spark-auth-filter/releases/tag/v1.2.2).

**Comment by idirze** [comment]
I close the issue. Fixed by [v1.2.2](https://github.com/OKDP/okdp-spark-auth-filter/releases/tag/v1.2.2).

**Comment by idirze** [comment]
@luiscinfo, a docker-compose setup was added to [test locally](https://github.com/OKDP/okdp-spark-auth-filter?tab=readme-ov-file#test-locally-using-docker-compose).
