### ISSUE TITLE
Serving Spark UI behind proxy

### ISSUE THREAD

**Issue by luiscinfo** [OKDP/okdp-spark-auth-filter#26]
Hi, 

We have tested this authentication filter and it meets most of our requirements. There is a feature that we would like this filter to have and it is the capability of serving the Spark UI in a subpath behind a proxy. 

Currently, it is harcoded that after the login, the filter redirects to the /home page of Spark UI. https://github.com/OKDP/okdp-spark-auth-filter/blob/83687e742dfb29627acc1ee3954c21d3b49938ea/src/main/java/io/okdp/spark/authc/OidcAuthFilter.java#L297

We serve the Spark application behind a proxy, in the path /spark. The filter authenticates correctly, but after login, it redirects to /home, and as a consecuence the redirection does not bring you to the Spark UI. We have locally tested to change the line previously referenced:

- In the OidcAuthFilter.java file

![image](https://github.com/OKDP/okdp-spark-auth-filter/assets/172381419/2e0f82c7-3cd6-433d-bb00-49066a4bf749)

- In the OidcAuthFilterTest.java file

![image](https://github.com/OKDP/okdp-spark-auth-filter/assets/172381419/9c0a3481-ee25-449f-ab5b-b9439a1f0835)

This works as spected, it allows the Spark UI to be served in a subpath behind a proxy.

**Comment by idirze** [comment]
Hello @luiscinfo,

Yes, in fact, the home page was hardcoded and hence not works behind a reverse proxy.


If you are interested by the contribution you can push us a pull request by modifying the line [OidcAuthFilter.java](https://github.com/OKDP/okdp-spark-auth-filter/blob/main/src/main/java/io/okdp/spark/authc/OidcAuthFilter.java#L295) with the following:

```console
      servletResponse
          .getWriter()
          .print(
              String.format(
                  "<script type=\"text/javascript\">window.location.href = '%s'</script>",
                  ((HttpServletRequest) servletRequest).getRequestURI()));
```

Apply the checkstyle before building:
```console
mvn spotless:apply
```
