### ISSUE TITLE
Detect and allow connection with an existing JWT token inside header

### ISSUE THREAD

**Issue by lioneloh** [OKDP/okdp-spark-auth-filter#34]
We should allow the okdp-spark-auth-filter to rely on an existing JWT token provided inside a header instead of asking the user to authenticate again.
It will allow authenticating reverse-proxy or gateway to authenticate the users and proxy the HTTP request to the spark UI with identity propagation.

Consider this use case :
[![](https://mermaid.ink/img/pako:eNqNUs1qwzAMfhXha9sXyKFQ2rF2MFaWjl1yEbbamCZ25tgtofTdJ-enDYHBbpH8_UnRTUirSCSipp9ARtJG48lhmRkAlN46WBVaUiwrdF5LXaHx8IqerthM2x-7zXraS7k4f-1iu5WCxXI5GwQS-Iy-tYcO0bcjpkNHgNKOpAdvW33YO3vRitxEMb4lsAo-J8PmLBQBLeMPtdEQD51nsLGSmmbrzeozHHlFb9-Hpxc_L8bjeafpQgNmJDIbVpPAi3Fa5rAl5Lngqn0e8bDHprDYmvfQ1vxB25B0TeVbLBoF0hHLQ0oyOFpbe9Y04Y6SpcSM7eGw54x1ZU1NnfGUPUq8GLb4X66Yi5JciVrxhd1iJxO81ZIykfCnoiOGwmciM3eGYvA2bYwUiXeB5sLZcMpFcsSi5ipUipP05_no8u_kI33vbrg95fsvvvfw_w?type=png)](https://mermaid.live/edit#pako:eNqNUs1qwzAMfhXha9sXyKFQ2rF2MFaWjl1yEbbamCZ25tgtofTdJ-enDYHBbpH8_UnRTUirSCSipp9ARtJG48lhmRkAlN46WBVaUiwrdF5LXaHx8IqerthM2x-7zXraS7k4f-1iu5WCxXI5GwQS-Iy-tYcO0bcjpkNHgNKOpAdvW33YO3vRitxEMb4lsAo-J8PmLBQBLeMPtdEQD51nsLGSmmbrzeozHHlFb9-Hpxc_L8bjeafpQgNmJDIbVpPAi3Fa5rAl5Lngqn0e8bDHprDYmvfQ1vxB25B0TeVbLBoF0hHLQ0oyOFpbe9Y04Y6SpcSM7eGw54x1ZU1NnfGUPUq8GLb4X66Yi5JciVrxhd1iJxO81ZIykfCnoiOGwmciM3eGYvA2bYwUiXeB5sLZcMpFcsSi5ipUipP05_no8u_kI33vbrg95fsvvvfw_w)

We need to have inside the JWT token all information needed (sub,email,groups claim, ...).

This Gateway could also avoid setting individual redirect URL for all SparkUI. Instead the Gateway will host the only redirect URL for all SparkUI

What do you think ?

I may help if we all agree on the scope.

**Comment by idirze** [comment]
Hello @lioneloh,

Thank you for the proposal, it will be a nice feature to have natively in the filter. So, please go ahead if you have time.

For information, we have planned to develop the gateway part (UI + Rest API) authenticated with OIDC. The gateway will discover automatically all the spark jobs running or completed in the cluster and list them in the UI (links, status, start/end time, etc). There will be one single URL for all spark jobs listed in the UI (Gateway URL). When the user clicks the url, the gateway renders the live spark UI if the job is still running or renders/redirects to spark history when the job was completed (failed, terminated). The gateway will also come with other features like monitoring, logging, optimisations, etc.

Your feature brings flexibility in the usage of the filter through a reverse proxy or an own existing gateway.

**Comment by idirze** [comment]
[v1.3.0](https://github.com/OKDP/okdp-spark-auth-filter/releases/tag/v1.3.0)
